"""initial schema

Revision ID: 3ec570f11235
Revises: 
Create Date: 2026-05-01 13:50:36.468374

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3ec570f11235'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('permissions', sa.String(length=32), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_tokens_token_hash'), ['token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('device_caches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('home_id', sa.String(length=64), nullable=True),
    sa.Column('did', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('spec_data', sa.JSON(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('cached_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'did', name='uk_device_caches_user_did')
    )
    with op.batch_alter_table('device_caches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_caches_user_id'), ['user_id'], unique=False)

    op.create_table('home_caches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('home_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('room_list', sa.JSON(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('cached_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'home_id', name='uk_home_caches_user_home')
    )
    with op.batch_alter_table('home_caches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_home_caches_user_id'), ['user_id'], unique=False)

    op.create_table('scene_caches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('home_id', sa.String(length=64), nullable=False),
    sa.Column('scene_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('cached_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'scene_id', name='uk_scene_caches_user_scene')
    )
    with op.batch_alter_table('scene_caches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scene_caches_user_id'), ['user_id'], unique=False)

    op.create_table('xiaomi_auths',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('auth_data', sa.JSON(), nullable=False),
    sa.Column('xiaomi_user_id', sa.String(length=64), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_refreshed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('xiaomi_auths', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_xiaomi_auths_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('xiaomi_auths', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_xiaomi_auths_user_id'))

    op.drop_table('xiaomi_auths')
    with op.batch_alter_table('scene_caches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scene_caches_user_id'))

    op.drop_table('scene_caches')
    with op.batch_alter_table('home_caches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_home_caches_user_id'))

    op.drop_table('home_caches')
    with op.batch_alter_table('device_caches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_caches_user_id'))

    op.drop_table('device_caches')
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_tokens_token_hash'))

    op.drop_table('api_tokens')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    # ### end Alembic commands ###
