"""add device_groups automation_rules energy_logs

Revision ID: 629e9ba8cbe7
Revises: 3ec570f11235
Create Date: 2026-05-01 20:10:59.558945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '629e9ba8cbe7'
down_revision = '3ec570f11235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('trigger_type', sa.String(length=32), nullable=False),
    sa.Column('trigger_config', sa.JSON(), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('action_config', sa.JSON(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('automation_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_automation_rules_user_id'), ['user_id'], unique=False)

    op.create_table('device_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('icon', sa.String(length=32), nullable=True),
    sa.Column('is_favorite_group', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uk_device_groups_user_name')
    )
    with op.batch_alter_table('device_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_groups_user_id'), ['user_id'], unique=False)

    op.create_table('energy_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('did', sa.String(length=64), nullable=False),
    sa.Column('prop_name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('energy_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_energy_logs_logged_at'), ['logged_at'], unique=False)
        batch_op.create_index('ix_energy_logs_user_did_logged', ['user_id', 'did', 'logged_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_energy_logs_user_id'), ['user_id'], unique=False)

    op.create_table('device_group_members',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device_caches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['device_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'device_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_group_members')
    with op.batch_alter_table('energy_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_energy_logs_user_id'))
        batch_op.drop_index('ix_energy_logs_user_did_logged')
        batch_op.drop_index(batch_op.f('ix_energy_logs_logged_at'))

    op.drop_table('energy_logs')
    with op.batch_alter_table('device_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_groups_user_id'))

    op.drop_table('device_groups')
    with op.batch_alter_table('automation_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_rules_user_id'))

    op.drop_table('automation_rules')
    # ### end Alembic commands ###
