"""add rated_power to device_caches

Revision ID: 9c53844fd677
Revises: 629e9ba8cbe7
Create Date: 2026-05-02 04:04:47.195594

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9c53844fd677'
down_revision = '629e9ba8cbe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_caches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rated_power', sa.Float(), nullable=True, comment='额定功率(W)，用于估算能耗'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_caches', schema=None) as batch_op:
        batch_op.drop_column('rated_power')

    # ### end Alembic commands ###
