"""add ble_devices and ble_sensor_readings tables

Revision ID: b19a97d4ddac
Revises: 9c53844fd677
Create Date: 2026-05-04 15:24:42.345736

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b19a97d4ddac'
down_revision = '9c53844fd677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ble_devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('did', sa.String(length=64), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=False),
    sa.Column('bindkey', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('did')
    )
    with op.batch_alter_table('ble_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ble_devices_user_id'), ['user_id'], unique=False)

    op.create_table('ble_sensor_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ble_device_id', sa.Integer(), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ble_device_id'], ['ble_devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ble_sensor_readings', schema=None) as batch_op:
        batch_op.create_index('ix_ble_readings_device_recorded', ['ble_device_id', 'recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ble_sensor_readings_ble_device_id'), ['ble_device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ble_sensor_readings_recorded_at'), ['recorded_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ble_sensor_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ble_sensor_readings_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_ble_sensor_readings_ble_device_id'))
        batch_op.drop_index('ix_ble_readings_device_recorded')

    op.drop_table('ble_sensor_readings')
    with op.batch_alter_table('ble_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ble_devices_user_id'))

    op.drop_table('ble_devices')
    # ### end Alembic commands ###
